### ISSUE TITLE
thread 'main' panicked at 'Could not parse Unreal C++ header file content

### ISSUE THREAD

**Issue by B1ackg0d** [PsichiX/unreal-doc#5] opened 2024-01-19 02:52 UTC
Hello, I am trying to use unreal-doc to build documentation in my personal project. I am currently encountering an error. Am I using it incorrectly? Thank you in advance for your help.
```
unreal-doc -i UnrealDoc.toml
thread 'main' panicked at 'Could not parse Unreal C++ header file content!
File: "\\\\?\\E:\\projectr\\Rhea\\Source\\Rhea\\Town\\Objects\\TownInfo.h"
Error:
  --> 31:74
   |
31 |    virtual UTownObjectComponent* GetTownObjectComponent() const override { return TownObjectComponent; }
   |                                                                            ^---
   |
   = expected snippet', src\main.rs:159:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
my toml：
```
input_dirs = [
    "./Source/Rhea/Town/Objects",
]
output_dir = "./Distribution"
#backend = "MdBook"
#
#[backend_mdbook]
#title = "Systems - Modular and scalable game architecture for orthogonal game logic"
#build = true
#cleanup = true
# header = "header.md"
# footer = "footer.md"
```

**Comment by PsichiX** [comment] 2024-01-19 03:00
Hi!
so the problem is that at this moment, `unreal-doc` does not support entire C++ syntax, which includes field initialization expressions and inline function body.

to solve that problem please use `ignore` comment wraps like this:
```cpp
virtual UTownObjectComponent* GetTownObjectComponent() const override {
  //// [ignore]
  return TownObjectComponent;
  //// [/ignore]
}
```

**Comment by B1ackg0d** [comment] 2024-01-19 03:37
> ```c++
> /// [ignore]
> ```

Thank you for your reply. As I have not written rust before, I don't know if you are using third-party libraries for AST parsing in your project. Is it an issue with these libraries? Or maybe we can consider introducing third-party tools or scripts to temporarily add ignore comments and then restore them after generation. I think this is a problem that needs to be solved. I am very interested in this and I hope to have the opportunity to join the development of this project. As mentioned in your project README, doxygen is too old-fashioned and complex, and I have tried many similar tools, none of which are as good. In summary, I think this is a great project. Thank you again for your work.

**Comment by PsichiX** [comment] 2024-01-19 03:52
thanks for the kind words!
i haven't found existing rust crate for parsing C++, i had to make PEG parser rules for it but i am open for introducing plugins-based extensions to `unreal-doc` that could serve as replaceable C++ and other input format parsers. if you have ideas for such i am open to hear them.

**Comment by PsichiX** [comment] 2024-02-05 21:51
@B1ackg0d published new version with function types support and better errors. Please tell me if works as expected, so we can close the issue or improve it :)

**Closed** 2024-02-06 02:10 UTC
